package com.gokrokve.knowledgebase.views;

import com.gokrokve.knowledgebase.samples.crud.CategoryField;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DocumentFormDesign extends CssLayout {
	protected TextField title;
    protected TextField author;
    protected TextField keywords;
    protected TextField content_type;
    protected TextField content_length;
    protected ComboBox language;
    protected Button save;
    protected Button cancel;
    protected Button delete;

	public DocumentFormDesign(){
	    Design.read(this);
	}

}
